use crate::core::expr::{Expr, OrderExpr};
use crate::core::query::SelectQuery;
use crate::core::types::Value;

/// PascalCase query builder wrapping `SelectQuery`.
///
/// Generated by `derive(Model)` for each model's `Find()`/`FindId()` methods.
/// Provides a fluent, PascalCase API matching Sentinel's public style.
#[must_use = "query does nothing until .FetchAll() or .Build() is called"]
pub struct ModelQuery {
    inner: SelectQuery,
}

impl ModelQuery {
    pub fn from_table(table: &str) -> Self {
        Self {
            inner: SelectQuery::new(table),
        }
    }

    pub fn from_select(select: SelectQuery) -> Self {
        Self { inner: select }
    }

    #[allow(non_snake_case)]
    pub fn Where(mut self, expr: Expr) -> Self {
        self.inner = self.inner.where_(expr);
        self
    }

    #[allow(non_snake_case)]
    pub fn OrderBy(mut self, order: OrderExpr) -> Self {
        self.inner = self.inner.order_by(order);
        self
    }

    #[allow(non_snake_case)]
    pub fn Limit(mut self, n: u64) -> Self {
        self.inner = self.inner.limit(n);
        self
    }

    #[allow(non_snake_case)]
    pub fn Offset(mut self, n: u64) -> Self {
        self.inner = self.inner.offset(n);
        self
    }

    #[allow(non_snake_case)]
    pub fn Build(&self) -> (String, Vec<Value>) {
        self.inner.build()
    }

    /// Access the inner `SelectQuery` for execution or further composition.
    pub fn into_inner(self) -> SelectQuery {
        self.inner
    }
}
